name: interestCircle


on:
  push:
    branches:
       main
  pull_request:
    branches:
       main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: 检查代码
        uses: actions/checkout@v2

      - name: 设置Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 安装依赖
        run: npm install

      - name: 运行测试
        run: npm test

      - name: 构建项目
        run: npm run dev
        
